spring:
  application:
    name: event-service
  cloud:
      config:
        discovery:
          enabled: true
        failFast: true
  profiles: cloud
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}